# Generated by Django 5.2.7 on 2025-11-10 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Alimento",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nome", models.CharField(max_length=100)),
                ("unidade", models.FloatField()),
                ("peso", models.FloatField()),
                ("valor", models.DecimalField(decimal_places=2, max_digits=10)),
                ("estoque", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Funcionario",
            fields=[
                ("matricula", models.AutoField(primary_key=True, serialize=False)),
                ("nome", models.CharField(max_length=100)),
                ("idade", models.IntegerField()),
                ("sexo", models.CharField(max_length=20)),
            ],
        ),
    ]
